name: Collection Docs
concurrency:
  group: docs-push-${{ github.sha }}
  cancel-in-progress: true
on:
  push:
    branches:
    - main
    - stable-*
    tags:
    - '*'
  schedule:
  - cron: '0 13 * * *'

jobs:
  build-docs:
    permissions:
      contents: read
    name: Build Ansible Docs
    uses: ansible-community/github-docs-build/.github/workflows/_shared-docs-build-push.yml@main
    with:
      init-lenient: true
      init-fail-on-error: true
      extra-collections: 'git+https://github.com/ansible-collections/amazon.aws.git,main'
      # Please also update docs-pr.yml
      provide-link-targets: |
        ansible_collections.amazon.aws.autoscaling_group_info_module
        ansible_collections.amazon.aws.autoscaling_group_module
        ansible_collections.amazon.aws.cloudtrail_module
        ansible_collections.amazon.aws.ec2_eip_info_module
        ansible_collections.amazon.aws.ec2_eip_module
        ansible_collections.amazon.aws.elb_application_lb_info_module
        ansible_collections.amazon.aws.elb_application_lb_module
        ansible_collections.amazon.aws.iam_policy_info_module
        ansible_collections.amazon.aws.iam_policy_module
        ansible_collections.amazon.aws.rds_cluster_info_module
        ansible_collections.amazon.aws.rds_cluster_module
        ansible_collections.amazon.aws.rds_cluster_snapshot_module
        ansible_collections.amazon.aws.rds_instance_info_module
        ansible_collections.amazon.aws.rds_instance_module
        ansible_collections.amazon.aws.rds_instance_snapshot_module
        ansible_collections.amazon.aws.rds_snapshot_info_module

  publish-docs-gh-pages:
    # use to prevent running on forks
    if: github.repository == 'ansible-collections/community.aws'
    permissions:
      contents: write
    needs: [build-docs]
    name: Publish Ansible Docs
    uses: ansible-community/github-docs-build/.github/workflows/_shared-docs-build-publish-gh-pages.yml@main
    with:
      artifact-name: ${{ needs.build-docs.outputs.artifact-name }}
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
